export enum ROUTE_ACCESS_TYPES {
  PUBLIC = 'PUBLIC',
  PRIVATE_NO_ROLE_CHECK = 'PRIVATE_NO_ROLE_CHECK',
  PRIVATE = 'PRIVATE',
  EXTERNAL_SERVICE = 'EXTERNAL_SERVICE',
}

export enum ROUTE_STATUSES {
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
}
